---
abstract: "Manage installation and migration of an application's (Postgres) database"
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pg-DatabaseManager
requires:
  DBI: 0
  File::Slurp: 0
  File::Which: 0
  List::AllUtils: 0
  Moose: 0
  MooseX::Getopt: 0
  MooseX::Params::Validate: 0.15
  MooseX::StrictConstructor: 0
  MooseX::Types: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  Pg::CLI: 0.04
  Test::Differences: 0
  Test::More: 0.88
  autodie: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Pg-DatabaseManager
  repository: http://hg.urth.org/hg/Pg-DatabaseManager
version: 0.04
