---
abstract: "Manage installation and migration of an application's (Postgres) database"
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pg-DatabaseManager
requires:
  Moose: 0
  Pg::CLI: 0.04
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Pg-DatabaseManager
  repository: http://hg.urth.org/hg/Pg-DatabaseManager
version: 0.01
